from django.urls import path

from .views import (
    delete_message_api,
    edit_message_api,
    inbox,
    message_pin_api,
    message_reaction_api,
    message_forward_api,
    message_save_api,
    moderation,
    moderation_export,
    notification_preference_api,
    participant_add_api,
    participant_update_api,
    room_messages_api,
    room_messages_export,
    room_search_api,
    room_typing_api,
    send_message_api,
    unread_summary_api,
)

urlpatterns = [
    path('', inbox, name='inbox'),
    path('moderation/', moderation, name='moderation'),
    path('moderation/export/', moderation_export, name='moderation_export'),
    path('api/unread-summary/', unread_summary_api, name='unread_summary_api'),
    path('api/room/<int:room_id>/messages/', room_messages_api, name='room_messages_api'),
    path('api/room/<int:room_id>/typing/', room_typing_api, name='room_typing_api'),
    path('api/room/<int:room_id>/search/', room_search_api, name='room_search_api'),
    path('api/room/<int:room_id>/send/', send_message_api, name='send_message_api'),
    path('api/room/<int:room_id>/message/<int:message_id>/edit/', edit_message_api, name='edit_message_api'),
    path('api/room/<int:room_id>/message/<int:message_id>/delete/', delete_message_api, name='delete_message_api'),
    path('api/room/<int:room_id>/message/<int:message_id>/react/', message_reaction_api, name='message_reaction_api'),
    path('api/room/<int:room_id>/message/<int:message_id>/pin/', message_pin_api, name='message_pin_api'),
    path('api/room/<int:room_id>/message/<int:message_id>/save/', message_save_api, name='message_save_api'),
    path('api/room/<int:room_id>/message/<int:message_id>/forward/', message_forward_api, name='message_forward_api'),
    path('api/room/<int:room_id>/notifications/', notification_preference_api, name='notification_preference_api'),
    path('api/room/<int:room_id>/participants/add/', participant_add_api, name='participant_add_api'),
    path('api/room/<int:room_id>/participants/update/', participant_update_api, name='participant_update_api'),
    path('room/<int:room_id>/', inbox, name='room'),
    path('room/<int:room_id>/export/', room_messages_export, name='room_messages_export'),
]
