from django.urls import path

from .views_api import (
    TeacherStudentsListJson,
    TeacherAssignedSubjectsListJson,
    TeacherEventListJson,
    TeacherAssignedClassFeeListJson,
    TeacherAssignedClassStudentsJson,
    get_assigned_class_list_api,
    get_assigned_student_list_by_class_api,
    TeacherStudentFeeDetailsByClassJson,
    TeacherStudentFeeDetailsByStudentJson,
    teacher_self_attendance_history_api,
    get_teacher_subject_note_bootstrap_api,
    get_teacher_subject_note_list_api,
    get_teacher_subject_note_detail_api,
    upsert_teacher_subject_note_api,
    toggle_teacher_subject_note_publish_api,
)
from .leave_views_api import (
    TeacherLeaveApplicationListJson,
    get_teacher_leave_type_list_api,
    teacher_apply_leave_api,
    teacher_cancel_leave_api,
    teacher_update_leave_api,
    get_teacher_leave_detail_api,
)

urlpatterns = [
    path('TeacherStudentsListJson', TeacherStudentsListJson.as_view(), name='TeacherStudentsListJson'),
    path('TeacherAssignedSubjectsListJson', TeacherAssignedSubjectsListJson.as_view(), name='TeacherAssignedSubjectsListJson'),
    path('get_assigned_class_list_api', get_assigned_class_list_api, name='get_assigned_class_list_api'),
    path('get_assigned_student_list_by_class_api', get_assigned_student_list_by_class_api, name='get_assigned_student_list_by_class_api'),
    path('TeacherAssignedClassStudentsJson', TeacherAssignedClassStudentsJson.as_view(), name='TeacherAssignedClassStudentsJson'),
    path('TeacherAssignedClassFeeListJson', TeacherAssignedClassFeeListJson.as_view(), name='TeacherAssignedClassFeeListJson'),
    path('TeacherStudentFeeDetailsByClassJson', TeacherStudentFeeDetailsByClassJson.as_view(), name='TeacherStudentFeeDetailsByClassJson'),
    path('TeacherStudentFeeDetailsByStudentJson', TeacherStudentFeeDetailsByStudentJson.as_view(), name='TeacherStudentFeeDetailsByStudentJson'),
    path('TeacherEventListJson', TeacherEventListJson.as_view(), name='TeacherEventListJson'),
    path('teacher_self_attendance_history_api', teacher_self_attendance_history_api, name='teacher_self_attendance_history_api'),
    path('get_teacher_subject_note_bootstrap_api', get_teacher_subject_note_bootstrap_api, name='get_teacher_subject_note_bootstrap_api'),
    path('get_teacher_subject_note_list_api', get_teacher_subject_note_list_api, name='get_teacher_subject_note_list_api'),
    path('get_teacher_subject_note_detail_api', get_teacher_subject_note_detail_api, name='get_teacher_subject_note_detail_api'),
    path('upsert_teacher_subject_note_api', upsert_teacher_subject_note_api, name='upsert_teacher_subject_note_api'),
    path('toggle_teacher_subject_note_publish_api', toggle_teacher_subject_note_publish_api, name='toggle_teacher_subject_note_publish_api'),
    path('TeacherLeaveApplicationListJson', TeacherLeaveApplicationListJson.as_view(), name='TeacherLeaveApplicationListJson'),
    path('get_teacher_leave_type_list_api', get_teacher_leave_type_list_api, name='get_teacher_leave_type_list_api'),
    path('teacher_apply_leave_api', teacher_apply_leave_api, name='teacher_apply_leave_api'),
    path('teacher_update_leave_api', teacher_update_leave_api, name='teacher_update_leave_api'),
    path('teacher_cancel_leave_api', teacher_cancel_leave_api, name='teacher_cancel_leave_api'),
    path('get_teacher_leave_detail_api', get_teacher_leave_detail_api, name='get_teacher_leave_detail_api'),
]
