# Generated by Django 5.2.10 on 2026-05-18 16:02

import django.db.models.deletion
import dynamic_filenames
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipientCategory', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('parent', 'Parent'), ('school', 'School')], default='student', max_length=20)),
                ('issueDate', models.DateField()),
                ('certificateNumber', models.CharField(db_index=True, max_length=120)),
                ('verificationToken', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('customTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('customSubtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('customBodyText', models.TextField(blank=True, null=True)),
                ('customFooterText', models.TextField(blank=True, null=True)),
                ('draftName', models.CharField(blank=True, max_length=200, null=True)),
                ('issuePayload', models.JSONField(blank=True, default=dict)),
                ('issueData', models.JSONField(blank=True, default=dict)),
                ('issueStatus', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled'), ('reissued', 'Reissued')], default='issued', max_length=20)),
                ('cancelledOn', models.DateTimeField(blank=True, null=True)),
                ('cancellationReason', models.TextField(blank=True, null=True)),
                ('designSnapshot', models.JSONField(blank=True, default=dict)),
                ('renderSnapshot', models.JSONField(blank=True, default=dict)),
                ('contextSnapshot', models.JSONField(blank=True, default=dict)),
                ('htmlSnapshot', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('lastEditedBy', models.CharField(blank=True, max_length=500, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Certificate Issues',
            },
        ),
        migrations.CreateModel(
            name='CertificateSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=80)),
                ('currentValue', models.PositiveIntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Certificate Sequences',
            },
        ),
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('recipientCategory', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('parent', 'Parent'), ('school', 'School')], default='student', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('defaultTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('defaultSubtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('defaultBodyTemplate', models.TextField(blank=True, null=True)),
                ('defaultFooterText', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isSystem', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('lastEditedBy', models.CharField(blank=True, max_length=500, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Certificate Types',
            },
        ),
        migrations.CreateModel(
            name='CertificateDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160)),
                ('designMode', models.CharField(choices=[('html', 'Structured HTML'), ('image_overlay', 'Image Overlay')], default='html', max_length=24)),
                ('templateKey', models.CharField(choices=[('classic_formal', 'Classic Formal'), ('modern_clean', 'Modern Clean'), ('ceremonial_gold', 'Ceremonial Gold'), ('academic_seal', 'Academic Seal'), ('heritage_script', 'Heritage Script'), ('minimal_duotone', 'Minimal Duotone'), ('split_panel', 'Split Panel'), ('ledger_grid', 'Ledger Grid'), ('laurel_frame', 'Laurel Frame'), ('ribbon_banner', 'Ribbon Banner'), ('royal_arc', 'Royal Arc'), ('editorial_grid', 'Editorial Grid'), ('crest_band', 'Crest Band'), ('award_plaque', 'Award Plaque'), ('navy_gold_shield', 'Navy Gold Shield'), ('black_gold_sweep', 'Black Gold Sweep'), ('cobalt_corner_lines', 'Cobalt Corner Lines'), ('ivory_gold_arch', 'Ivory Gold Arch'), ('sapphire_wave_frame', 'Sapphire Wave Frame'), ('emerald_gold_ribbon', 'Emerald Gold Ribbon'), ('maroon_gold_gate', 'Maroon Gold Gate'), ('charcoal_orbit_frame', 'Charcoal Orbit Frame'), ('royal_blue_plaque', 'Royal Blue Plaque'), ('pearl_gold_corners', 'Pearl Gold Corners'), ('slate_gold_diagonal', 'Slate Gold Diagonal'), ('indigo_bottom_flourish', 'Indigo Bottom Flourish'), ('hand_fill_form', 'Hand-Fill Form'), ('prize_day_form', 'Prize Day Form'), ('custom', 'Custom')], default='classic_formal', max_length=40)),
                ('pageSize', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5'), ('LETTER', 'Letter'), ('CUSTOM', 'Custom')], default='A4', max_length=20)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=20)),
                ('pageWidthMm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('pageHeightMm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('marginTopMm', models.DecimalField(decimal_places=2, default=12, max_digits=6)),
                ('marginRightMm', models.DecimalField(decimal_places=2, default=12, max_digits=6)),
                ('marginBottomMm', models.DecimalField(decimal_places=2, default=12, max_digits=6)),
                ('marginLeftMm', models.DecimalField(decimal_places=2, default=12, max_digits=6)),
                ('titleAlignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=20)),
                ('bodyAlignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=20)),
                ('borderStyle', models.CharField(choices=[('none', 'None'), ('single', 'Single Border'), ('double', 'Double Border'), ('ornate', 'Ornate'), ('ribbon', 'Ribbon'), ('hairline', 'Hairline'), ('thick', 'Thick Frame'), ('inner_line', 'Inner Line'), ('triple', 'Triple Frame'), ('corner_marks', 'Corner Marks'), ('corner_flourish', 'Corner Flourish'), ('side_bars', 'Side Bars'), ('top_bottom', 'Top & Bottom'), ('dotted', 'Dotted'), ('dashed', 'Dashed'), ('ledger', 'Ledger Rule'), ('laurel', 'Laurel'), ('plaque', 'Plaque'), ('modern_frame', 'Modern Frame'), ('classic_frame', 'Classic Frame')], default='single', max_length=20)),
                ('fontFamily', models.CharField(blank=True, default='Georgia', max_length=120, null=True)),
                ('accentColor', models.CharField(blank=True, default='#1d4ed8', max_length=20, null=True)),
                ('textColor', models.CharField(blank=True, default='#1f2937', max_length=20, null=True)),
                ('backgroundColor', models.CharField(blank=True, default='#ffffff', max_length=20, null=True)),
                ('backgroundImage', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=dynamic_filenames.FilePattern(filename_pattern='my_model/{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}'), variations={'medium': (640, 640), 'thumbnail': (160, 160, True)})),
                ('assetConfig', models.JSONField(blank=True, default=dict)),
                ('layoutConfig', models.JSONField(blank=True, default=dict)),
                ('themeConfig', models.JSONField(blank=True, default=dict)),
                ('designSchema', models.JSONField(blank=True, default=dict)),
                ('designJson', models.JSONField(blank=True, default=dict)),
                ('mergeSchema', models.JSONField(blank=True, default=list)),
                ('designVersion', models.PositiveIntegerField(default=1)),
                ('customHeaderText', models.CharField(blank=True, max_length=255, null=True)),
                ('customFooterText', models.CharField(blank=True, max_length=500, null=True)),
                ('customCss', models.TextField(blank=True, null=True)),
                ('overlaySchema', models.JSONField(blank=True, default=list)),
                ('showLogo', models.BooleanField(default=True)),
                ('showSignatureLine', models.BooleanField(default=True)),
                ('showSeal', models.BooleanField(default=True)),
                ('isDraft', models.BooleanField(default=False)),
                ('isDefaultForType', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('isSystem', models.BooleanField(default=False)),
                ('isCustom', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('lastEditedBy', models.CharField(blank=True, max_length=500, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('basedOnDesignID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivedDesigns', to='certificateApp.certificatedesign')),
            ],
            options={
                'verbose_name_plural': 'Certificate Designs',
            },
        ),
    ]
