# Generated by Django 5.2.10 on 2026-05-18 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificateApp', '0001_initial'),
        ('homeApp', '0001_initial'),
        ('managementApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatedesign',
            name='schoolID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schooldetail'),
        ),
        migrations.AddField(
            model_name='certificatedesign',
            name='updatedByUserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='cancelledByUserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='certificateDesignID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificateApp.certificatedesign'),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='parentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementApp.parent'),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='reissuedFromIssueID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reissuedIssues', to='certificateApp.certificateissue'),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='schoolID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schooldetail'),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='sessionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schoolsession'),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='studentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementApp.student'),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='teacherID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementApp.teacherdetail'),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='updatedByUserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificatesequence',
            name='schoolID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schooldetail'),
        ),
        migrations.AddField(
            model_name='certificatesequence',
            name='sessionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schoolsession'),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='schoolID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schooldetail'),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='updatedByUserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificatesequence',
            name='certificateTypeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificateApp.certificatetype'),
        ),
        migrations.AddField(
            model_name='certificateissue',
            name='certificateTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificateApp.certificatetype'),
        ),
        migrations.AddField(
            model_name='certificatedesign',
            name='certificateTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificateApp.certificatetype'),
        ),
        migrations.AddIndex(
            model_name='certificatetype',
            index=models.Index(fields=['schoolID', 'slug', 'isDeleted'], name='cert_type_school_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatetype',
            index=models.Index(fields=['recipientCategory', 'isActive'], name='cert_type_rec_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificatetype',
            constraint=models.UniqueConstraint(fields=('schoolID', 'slug'), name='cert_type_school_slug_uniq'),
        ),
        migrations.AddIndex(
            model_name='certificatesequence',
            index=models.Index(fields=['schoolID', 'sessionID'], name='cert_seq_school_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificatesequence',
            constraint=models.UniqueConstraint(fields=('schoolID', 'sessionID', 'certificateTypeID', 'prefix'), name='cert_seq_scope_prefix_uniq'),
        ),
        migrations.AddIndex(
            model_name='certificateissue',
            index=models.Index(fields=['schoolID', 'sessionID', 'recipientCategory'], name='cert_issue_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateissue',
            index=models.Index(fields=['issueDate', 'isDeleted'], name='cert_issue_date_del_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateissue',
            index=models.Index(fields=['schoolID', 'issueStatus', 'issueDate'], name='cert_issue_school_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificateissue',
            constraint=models.UniqueConstraint(fields=('schoolID', 'certificateNumber'), name='cert_issue_school_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='certificatedesign',
            index=models.Index(fields=['schoolID', 'certificateTypeID', 'isDeleted'], name='cert_design_school_type_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatedesign',
            index=models.Index(fields=['isActive', 'isCustom'], name='cert_design_active_custom_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatedesign',
            index=models.Index(fields=['schoolID', 'status', 'isDeleted'], name='cert_design_school_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificatedesign',
            constraint=models.UniqueConstraint(fields=('certificateTypeID', 'schoolID', 'slug'), name='cert_design_type_school_slug_uniq'),
        ),
    ]
