from django.urls import path

from libraryApp.api import views_api


urlpatterns = [
    path('dashboard_summary', views_api.dashboard_summary, name='dashboard_summary'),
    path('options', views_api.library_options_api, name='library_options_api'),
    path('available_copies', views_api.available_copies_api, name='available_copies_api'),
    path('member_eligibility', views_api.member_eligibility_api, name='member_eligibility_api'),
    path('settings_detail', views_api.settings_detail_api, name='settings_detail_api'),
    path('settings', views_api.settings_api, name='settings_api'),
    path('detail', views_api.detail_api, name='detail_api'),
    path('issue_history', views_api.issue_history_api, name='issue_history_api'),
    path('issue_detail', views_api.issue_detail_api, name='issue_detail_api'),
    path('delete', views_api.delete_api, name='delete_api'),
    path('report_csv', views_api.library_report_csv, name='library_report_csv'),
    path('CategoryListJson', views_api.LibraryCategoryListJson.as_view(), name='CategoryListJson'),
    path('AuthorListJson', views_api.LibraryAuthorListJson.as_view(), name='AuthorListJson'),
    path('PublisherListJson', views_api.LibraryPublisherListJson.as_view(), name='PublisherListJson'),
    path('BookListJson', views_api.LibraryBookListJson.as_view(), name='BookListJson'),
    path('BookCopyListJson', views_api.LibraryBookCopyListJson.as_view(), name='BookCopyListJson'),
    path('MemberListJson', views_api.LibraryMemberListJson.as_view(), name='MemberListJson'),
    path('IssueListJson', views_api.LibraryIssueListJson.as_view(), name='IssueListJson'),
    path('ReservationListJson', views_api.LibraryReservationListJson.as_view(), name='ReservationListJson'),
    path('FineListJson', views_api.LibraryFineListJson.as_view(), name='FineListJson'),
    path('OverdueReportListJson', views_api.LibraryOverdueReportListJson.as_view(), name='OverdueReportListJson'),
    path('category', views_api.category_api, name='category_api'),
    path('author', views_api.author_api, name='author_api'),
    path('publisher', views_api.publisher_api, name='publisher_api'),
    path('book', views_api.book_api, name='book_api'),
    path('copy', views_api.copy_api, name='copy_api'),
    path('bulk_copy', views_api.bulk_copy_api, name='bulk_copy_api'),
    path('member', views_api.member_api, name='member_api'),
    path('issue_book', views_api.issue_book_api, name='issue_book_api'),
    path('issue_reservation', views_api.issue_reservation_api, name='issue_reservation_api'),
    path('return_book', views_api.return_book_api, name='return_book_api'),
    path('renew_book', views_api.renew_book_api, name='renew_book_api'),
    path('reservation', views_api.reservation_api, name='reservation_api'),
    path('fine', views_api.fine_api, name='fine_api'),
    path('pay_fine', views_api.pay_fine_api, name='pay_fine_api'),
    path('waive_fine', views_api.waive_fine_api, name='waive_fine_api'),
    path('save_member_card_design', views_api.save_member_card_design_api, name='save_member_card_design_api'),
]
