# Generated by Django 4.2.8 on 2024-03-07 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dynamic_filenames
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_schooldetail_isdeleted_schoolowner_isdeleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managementApp', '0005_teacherdetail_salary_alter_teacherdetail_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatherName', models.CharField(blank=True, max_length=500, null=True)),
                ('motherName', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('profession', models.CharField(blank=True, max_length=500, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('lastEditedBy', models.CharField(blank=True, max_length=500, null=True)),
                ('schoolID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schooldetail')),
                ('sessionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schoolsession')),
            ],
            options={
                'verbose_name_plural': 'j)Parent Details',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(blank=True, max_length=500, null=True)),
                ('registrationCode', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('bloodGroup', models.CharField(blank=True, max_length=500, null=True)),
                ('presentAddress', models.TextField(blank=True, null=True)),
                ('presentPinCode', models.CharField(blank=True, max_length=500, null=True)),
                ('presentCity', models.CharField(blank=True, max_length=500, null=True)),
                ('presentState', models.CharField(blank=True, max_length=500, null=True)),
                ('presentCountry', models.CharField(blank=True, max_length=500, null=True)),
                ('permanentAddress', models.TextField(blank=True, null=True)),
                ('permanentPinCode', models.CharField(blank=True, max_length=500, null=True)),
                ('permanentCity', models.CharField(blank=True, max_length=500, null=True)),
                ('permanentState', models.CharField(blank=True, max_length=500, null=True)),
                ('permanentCountry', models.CharField(blank=True, max_length=500, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('photo', stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to=dynamic_filenames.FilePattern(filename_pattern='my_model/{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}'), variations={'medium': (250, 250), 'thumbnail': (100, 100, True)})),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('password', models.CharField(blank=True, max_length=500, null=True)),
                ('dateOfJoining', models.DateField(blank=True, null=True)),
                ('dateOfLeaving', models.DateField(blank=True, null=True)),
                ('additionalDetails', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('isActive', models.CharField(blank=True, default='Yes', max_length=200, null=True)),
                ('admissionFee', models.FloatField(default=0.0)),
                ('tuitionFee', models.FloatField(default=0.0)),
                ('isDeleted', models.BooleanField(default=False)),
                ('lastEditedBy', models.CharField(blank=True, max_length=500, null=True)),
                ('parentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managementApp.parent')),
                ('schoolID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schooldetail')),
                ('sessionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schoolsession')),
                ('standardID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managementApp.standard')),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'g) Student Details',
            },
        ),
    ]
