# Generated by Django 4.2.8 on 2024-03-08 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_schooldetail_isdeleted_schoolowner_isdeleted_and_more'),
        ('managementApp', '0006_parent_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignSubjectsToTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectBranch', models.CharField(blank=True, max_length=500, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('lastEditedBy', models.CharField(blank=True, max_length=500, null=True)),
                ('assignedSubjectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managementApp.assignsubjectstoclass')),
                ('schoolID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schooldetail')),
                ('sessionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schoolsession')),
                ('teacherID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managementApp.teacherdetail')),
            ],
            options={
                'verbose_name_plural': 'j) Assign Subjects To Class Details',
            },
        ),
    ]
