# Generated by Django 4.2.8 on 2024-03-10 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_schooldetail_isdeleted_schoolowner_isdeleted_and_more'),
        ('managementApp', '0009_assignexamtoclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignexamtoclass',
            options={'verbose_name_plural': 'j) Assign Exam To Class Details'},
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPresent', models.BooleanField(default=False)),
                ('isHoliday', models.BooleanField(default=False)),
                ('bySubject', models.BooleanField(default=False)),
                ('attendanceDate', models.DateTimeField(blank=True, null=True)),
                ('absentReason', models.CharField(blank=True, max_length=500, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('schoolID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schooldetail')),
                ('sessionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schoolsession')),
                ('standardID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managementApp.standard')),
                ('studentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managementApp.student')),
                ('subjectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managementApp.subjects')),
            ],
            options={
                'verbose_name_plural': 'p) Student Attendance',
            },
        ),
    ]
