# Generated by Django 4.2.8 on 2024-03-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0010_alter_assignexamtoclass_options_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='lastEditedBy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
