# Generated by Django 4.2.8 on 2024-03-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_schooldetail_isdeleted_schoolowner_isdeleted_and_more'),
        ('managementApp', '0012_alter_studentattendance_absentreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPresent', models.BooleanField(default=False)),
                ('isHoliday', models.BooleanField(default=False)),
                ('attendanceDate', models.DateTimeField(blank=True, null=True)),
                ('absentReason', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('lastEditedBy', models.CharField(blank=True, max_length=500, null=True)),
                ('schoolID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schooldetail')),
                ('sessionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schoolsession')),
                ('teacherID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managementApp.teacherdetail')),
            ],
            options={
                'verbose_name_plural': 'q) Teacher Attendance',
            },
        ),
    ]
