# Generated by Django 4.2.8 on 2024-03-16 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_schooldetail_isdeleted_schoolowner_isdeleted_and_more'),
        ('managementApp', '0013_teacherattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, max_length=500, null=True)),
                ('payDate', models.DateField(blank=True, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('lastEditedBy', models.CharField(blank=True, max_length=500, null=True)),
                ('schoolID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schooldetail')),
                ('sessionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schoolsession')),
                ('studentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managementApp.student')),
            ],
            options={
                'verbose_name_plural': 'r) Student Fee',
            },
        ),
    ]
