# Generated by Django 4.2.8 on 2024-03-16 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0014_studentfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='standardID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managementApp.standard'),
        ),
    ]
