# Generated by Django 4.2.8 on 2024-03-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0015_studentfee_standardid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='amount',
            field=models.FloatField(null=0.0),
        ),
    ]
