# Generated by Django 4.2.8 on 2024-03-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0016_alter_studentfee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
