# Generated by Django 4.2.8 on 2024-03-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0017_alter_studentfee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
