# Generated by Django 4.2.8 on 2024-03-25 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0019_markofstudentsbyexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='markofstudentsbyexam',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='markofstudentsbyexam',
            name='examID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managementApp.assignexamtoclass'),
        ),
    ]
