# Generated by Django 5.2.10 on 2026-02-01 21:56

import django.db.models.deletion
import dynamic_filenames
import stdimage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('password', models.CharField(blank=True, max_length=500, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('userGroup', models.CharField(blank=True, max_length=500, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('lastEditedBy', models.CharField(blank=True, max_length=500, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'a) School Owner.',
            },
        ),
        migrations.CreateModel(
            name='SchoolDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('logo', stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to=dynamic_filenames.FilePattern(filename_pattern='my_model/{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}'), variations={'medium': (250, 250), 'thumbnail': (100, 100, True)})),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=500, null=True)),
                ('pinCode', models.CharField(blank=True, max_length=15, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('lastEditedBy', models.CharField(blank=True, max_length=500, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('ownerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schoolowner')),
            ],
            options={
                'verbose_name_plural': 'b) School Detail.',
            },
        ),
        migrations.CreateModel(
            name='SchoolSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionYear', models.CharField(blank=True, max_length=500, null=True)),
                ('isCurrent', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('lastEditedBy', models.CharField(blank=True, max_length=500, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('schoolID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schooldetail')),
            ],
            options={
                'verbose_name_plural': 'd) School Session.',
            },
        ),
        migrations.CreateModel(
            name='SchoolSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, default='N/A', max_length=500, null=True)),
                ('twitter', models.CharField(blank=True, default='N/A', max_length=500, null=True)),
                ('googlePlus', models.CharField(blank=True, default='N/A', max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, default='N/A', max_length=500, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('lastEditedBy', models.CharField(blank=True, max_length=500, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('schoolID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeApp.schooldetail')),
            ],
            options={
                'verbose_name_plural': 'c) School Social Links.',
            },
        ),
    ]
