# Generated by Django 4.2.8 on 2023-12-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetail',
            name='lastEditedBy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='schoolowner',
            name='lastEditedBy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='schoolsession',
            name='lastEditedBy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='schoolsociallink',
            name='lastEditedBy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
