# Generated by Django 4.2.8 on 2023-12-31 17:16

from django.db import migrations
import dynamic_filenames
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_schooldetail_lasteditedby_schoolowner_lasteditedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldetail',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to=dynamic_filenames.FilePattern(filename_pattern='my_model/{app_label:.25}/{model_name:.30}/{uuid:base32}{ext}'), variations={'medium': (250, 250), 'thumbnail': (100, 100, True)}),
        ),
    ]
