# Generated by Django 4.2.8 on 2024-01-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_alter_schooldetail_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetail',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolowner',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolsession',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolsociallink',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
