from django.urls import path

from hostelApp.api import views_api


urlpatterns = [
    path('dashboard_summary', views_api.dashboard_summary, name='dashboard_summary'),
    path('report_summary', views_api.hostel_report_summary_api, name='hostel_report_summary_api'),
    path('resident_manifest_csv', views_api.resident_manifest_csv, name='resident_manifest_csv'),
    path('AdmissionListJson', views_api.HostelAdmissionListJson.as_view(), name='AdmissionListJson'),
    path('BuildingListJson', views_api.HostelBuildingListJson.as_view(), name='BuildingListJson'),
    path('FloorListJson', views_api.HostelFloorListJson.as_view(), name='FloorListJson'),
    path('RoomTypeListJson', views_api.HostelRoomTypeListJson.as_view(), name='RoomTypeListJson'),
    path('RoomListJson', views_api.HostelRoomListJson.as_view(), name='RoomListJson'),
    path('BedListJson', views_api.HostelBedListJson.as_view(), name='BedListJson'),
    path('AssignmentListJson', views_api.HostelAssignmentListJson.as_view(), name='AssignmentListJson'),
    path('FeeMappingListJson', views_api.HostelFeeMappingListJson.as_view(), name='FeeMappingListJson'),
    path('FeeRecordListJson', views_api.HostelFeeRecordListJson.as_view(), name='FeeRecordListJson'),
    path('options', views_api.hostel_options_api, name='hostel_options_api'),
    path('student_options', views_api.student_options_api, name='student_options_api'),
    path('resident_options', views_api.resident_options_api, name='resident_options_api'),
    path('admissions', views_api.admissions_api, name='admissions_api'),
    path('admission_detail', views_api.admission_detail_api, name='admission_detail_api'),
    path('delete_admission', views_api.delete_admission_api, name='delete_admission_api'),
    path('buildings', views_api.buildings_api, name='buildings_api'),
    path('building_detail', views_api.building_detail_api, name='building_detail_api'),
    path('delete_building', views_api.delete_building_api, name='delete_building_api'),
    path('floors', views_api.floors_api, name='floors_api'),
    path('floor_detail', views_api.floor_detail_api, name='floor_detail_api'),
    path('delete_floor', views_api.delete_floor_api, name='delete_floor_api'),
    path('room_types', views_api.room_types_api, name='room_types_api'),
    path('room_type_detail', views_api.room_type_detail_api, name='room_type_detail_api'),
    path('delete_room_type', views_api.delete_room_type_api, name='delete_room_type_api'),
    path('rooms', views_api.rooms_api, name='rooms_api'),
    path('room_detail', views_api.room_detail_api, name='room_detail_api'),
    path('delete_room', views_api.delete_room_api, name='delete_room_api'),
    path('beds', views_api.beds_api, name='beds_api'),
    path('bed_detail', views_api.bed_detail_api, name='bed_detail_api'),
    path('delete_bed', views_api.delete_bed_api, name='delete_bed_api'),
    path('assignments', views_api.assignments_api, name='assignments_api'),
    path('assignment_detail', views_api.assignment_detail_api, name='assignment_detail_api'),
    path('delete_assignment', views_api.delete_assignment_api, name='delete_assignment_api'),
    path('fee_mappings', views_api.fee_mappings_api, name='fee_mappings_api'),
    path('fee_mapping_detail', views_api.fee_mapping_detail_api, name='fee_mapping_detail_api'),
    path('delete_fee_mapping', views_api.delete_fee_mapping_api, name='delete_fee_mapping_api'),
    path('generate_fee_records', views_api.generate_hostel_fee_records_api, name='generate_hostel_fee_records_api'),
    path('fee_record_detail', views_api.hostel_fee_record_detail_api, name='hostel_fee_record_detail_api'),
    path('record_fee_payment', views_api.record_hostel_fee_payment_api, name='record_hostel_fee_payment_api'),
    path('update_fee_status', views_api.update_hostel_fee_status_api, name='update_hostel_fee_status_api'),
]
